[book]
authors = ["Nik Revenco"]
language = "en"
multilingual = false
src = "src"
title = "Helix Golf"
description = "Using Helix to its true potential"

[output.html]
site-url = "https://nik-rev.github.io/helix-golf"
git-repository-url = "https://github.com/nik-rev/helix-golf"
edit-url-template = "https://github.com/nik-rev/helix-golf/edit/main/{path}"

[preprocessor.helix-golf]
command = "cargo run --manifest-path scripts/Cargo.toml -- mdbook-preprocessor"
