theme = "catppuccin_mocha"
[editor.gutters]
layout = ["line-numbers", "spacer"]

[keys.normal]

# Original: Alt + s
C-s = "split_selection_on_newline"

# Original: Alt + J
C-y = "join_selections_space"

# Original: Alt + (
C-z = "rotate_selection_contents_backward"

# Original: Alt + )
#"C-g" = "rotate_selection_contents_forward"

#"C-M" = "remove_primary_selection"



[keys.select]

# Original: Alt + s
C-s = "split_selection_on_newline"

# Original: Alt + J
C-y = "join_selections_space"

# Original: Alt + (
C-z = "rotate_selection_contents_backward"

# Original: Alt + )
#"C-g" = "rotate_selection_contents_forward"

#"C-M" = "remove_primary_selection"

