name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: actions/setup-go@v3

      - name: Install VHS
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg
          sudo snap install ttyd --classic
          go install github.com/charmbracelet/vhs@v0.9

      - run: cargo generate-demos

      - name: Build mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "0.4.50"

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages
